export const RESET_QUESTION_LIST = 'RESET_QUESTION_LIST';
export const PUSH_QUESTION = 'PUSH_QUESTION';
export const SET_QUESTION = 'SET_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';