version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run test

  bump_patch_version:
      docker:
        - image: circleci/node:11.9
      working_directory: ~/repo
      steps:
        - checkout
        - run:
            name: Bump patch version
            command: |
                git config user.email "$GIT_USER_EMAIL"
                git config user.name "$GIT_USER_NAME"
                yarn run update-patch
                git push origin dev
                git push --tags

  deploy:
    docker:
      - image: circleci/node:11.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn run prod
      - run: yarn run deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - bump_patch_version:
          requires:
            - build
          filters:
            branches:
              only: dev
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master